### ISSUE TITLE
Cannot deploy via Docker Container

### ISSUE THREAD

**Issue by roberto-goncalves** [spring-cloud/spring-cloud-deployer-local#61]
Hi, I'm having problems related with deploying a stream using the :
``spring-cloud-deployer-local-1.2.2.BUILD-SNAPSHOT.jar``
and my Dockerfile builded with server-local is:
FROM nimmis/java-centos
MAINTAINER Roberto Gonçalves "roberto.forsaken@gmail.com"
RUN mkdir -p spring-log
VOLUME spring-log
EXPOSE 7000-7010
RUN wget -O app.jar http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-server-local/1.2.3.BUILD-SNAPSHOT/spring-cloud-dataflow-server-local-1.2.3.BUILD-SNAPSHOT.jar
ENV JAVA_OPTS="-Djava.io.tmpdir=spring-log"
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar ./app.jar" ]

So then I build the image and then i started it, so I get the docker+rabbitmq and do the bulk:

``app import http://bit.ly/Bacon-RELEASE-stream-applications-rabbit-docker``

So when I run:

``stream deploy --name ticktock``

I get:

``Caused by: java.io.IOException: Cannot run program "docker" (in directory "/root/spring-log/spring-cloud-dataflow-1938563371549328050/ticktock-1499481317911/ticktock.time"): error=2, No such file or directory``

Tracking down I found:

``at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.start(LocalAppDeployer.java:298) ~[spring-cloud-deployer-local-1.2.2.BUILD-SNAPSHOT.jar!/:1.2.2.BUILD-SNAPSHOT``

Checking this method and seeing the createDir method, I'm thinking that is a problem with creating the directory, but, I can't solve this since that I am new to this repository. Can you guys help me? Thank you!

**Comment by trisberg** [comment]
We don't recommend deploying the server as a docker container and then launch the apps as docker containers as well since the apps would be deployed in the same container that the server is running in and you'd need to have the docker executable available there. The local server is intended to run as a Java process on your local machine for testing and demo purposes. If you really want to deploy apps as docker containers take a look at the Kubernetes version of the server: http://cloud.spring.io/spring-cloud-dataflow-server-kubernetes/
